### ISSUE TITLE
Is there any problem？

### ISSUE THREAD

**Issue by T8star1984** [alexisrolland/ComfyUI-AuraSR#1]
I have tried many pictures, but the display effect of the project is much worse. The pictures have not become clearer, and there are obvious artifacts with excessive sharpening

**Comment by alexisrolland** [comment]
Hi @T8star1984,

This repository is just a ComfyUI node wrapping the original model and code of AuraSR coming from here: https://github.com/fal-ai/aura-sr

I would suggest you share your feedback to the author of AuraSR on that repo. I would also suggest you include examples of inputs and outputs you got.

From the limited tests I have done. I agree the results were a bit disappointing.

**Comment by jkla139** [comment]
Experiences of usage are in [cog-aura-sr](https://github.com/zsxkib/cog-aura-sr?tab=readme-ov-file#things-to-know-%EF%B8%8F) .
