### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by T8mars** [alexisrolland/ComfyUI-AuraSR#5]
HI,I use the AuraSr model,but it show error

![image](https://github.com/user-attachments/assets/077fa0bc-8cac-4d6c-8e7b-2506dbd90e56)

**Comment by alexisrolland** [comment]
Hi, this is because the Python library aura-sr is not up to date in your Python environment.

You can try to update it by re-installing the requirements.txt

Go to the custom_nodes folder and run:
..\..\python_embeded\python.exe -s -m pip install -r .\ComfyUI-AuraSR\requirements.txt

**Comment by T8mars** [comment]
okay,thans,let me try

**Comment by T8mars** [comment]
It's done,thanks
