### ISSUE TITLE
Where does AuraSR model download to?

### ISSUE THREAD

**Issue by ChangoMan** [alexisrolland/ComfyUI-AuraSR#6]
Thank for this node! One question I had is when I run the "Download AuraSR" node, where does it save those files to?

**Comment by alexisrolland** [comment]
Hello,
The node is using the method `AuraSR.from_pretrained()` from the `aura_sr` Python library. It's downloading the model in the Hugging Face cache folder: `C:\Users\yourwindowsuser\.cache\huggingface\hub`. I think this is displayed in the logs of ComfyUI.
